// Generated by CoffeeScript 1.3.3
(function() {

  window.getElementsList = function() {
    var createRandomObject, range1, range2, _i, _j, _k, _results, _results1, _results2;
    range1 = (function() {
      _results = [];
      for (_i = 1; _i <= 100; _i++){ _results.push(_i); }
      return _results;
    }).apply(this);
    range2 = (function() {
      _results1 = [];
      for (_j = 200; _j <= 1200; _j++){ _results1.push(_j); }
      return _results1;
    }).apply(this);
    createRandomObject = function(index) {
      return {
        value1: "ABC" + index,
        value2: "" + range1[Math.round(Math.random() * (range1.length - 1))] + "%",
        value3: range2[Math.round(Math.random() * (range2.length - 1))],
        imageType: ['up', 'down', 'stable'][Math.round(Math.random() * 2)],
        unicode: ['▲', '►', '▼'][Math.round(Math.random() * 2)]
      };
    };
    return (function() {
      _results2 = [];
      for (_k = 1; _k <= 40; _k++){ _results2.push(_k); }
      return _results2;
    }).apply(this).map(createRandomObject);
  };

}).call(this);
