// Generated by CoffeeScript 1.3.3
(function() {
  var ContextCreator;

  ContextCreator = (function() {
    var imagePosition, textPosition;

    textPosition = {
      y: 18
    };

    imagePosition = {
      y: 5
    };

    function ContextCreator(id, initialPosition) {
      if (initialPosition == null) {
        initialPosition = 5;
      }
      this.canvas = document.getElementById(id);
      this.context = this.canvas.getContext('2d');
      this.context.font = '15px Arial';
      this.position = initialPosition;
    }

    ContextCreator.prototype.fillPlainText = function(text) {
      return this.context.fillText(text, this.position, textPosition.y);
    };

    return ContextCreator;

  })();

  $(function() {
    var addElements, animate, canvas, currentPosition, delayedAnimation, index, message, refreshMessageList, startPosition, textWidth, toggleTicker, wrappedContext;
    index = 0;
    startPosition = 800;
    wrappedContext = new ContextCreator('ticker-with-plain-text', startPosition);
    canvas = wrappedContext.canvas;
    currentPosition = startPosition;
    message = '';
    toggleTicker = false;
    refreshMessageList = function() {
      var i, msg, _i, _ref;
      msg = '';
      for (i = _i = index, _ref = index + 14; index <= _ref ? _i <= _ref : _i >= _ref; i = index <= _ref ? ++_i : --_i) {
        msg += "AAPL +5" + i + " ";
      }
      return message = msg;
    };
    addElements = function() {
      return wrappedContext.fillPlainText(message);
    };
    refreshMessageList();
    addElements();
    textWidth = wrappedContext.context.measureText(message).width;
    animate = function() {
      if (toggleTicker) {
        currentPosition -= 1;
        wrappedContext.context.clearRect(0, 0, canvas.width, canvas.height);
        wrappedContext.position = currentPosition;
        addElements();
        if ((currentPosition + textWidth) < canvas.width) {
          wrappedContext.position = currentPosition + textWidth;
          addElements();
        }
        if (currentPosition < -textWidth) {
          currentPosition += textWidth;
          return refreshMessageList();
        }
      }
    };
    delayedAnimation = function() {
      return setInterval(animate, 33);
    };
    setTimeout(delayedAnimation, 2000);
    return $('.ticker-with-plain-text').find('button').click(function() {
      return toggleTicker = !toggleTicker;
    });
  });

}).call(this);
